options:
    IOPT:
      kind: integer
      default: 0

    IBRION:
      kind: integer
      default: 0
      values:
         - 0
         - 1
         - 2
         - 3
         - 4
                

    NSW:
      kind: integer
      default: 100
  
    EDIFFG:
      kind: float
      default: -0.01
  
    POTIM:
      kind: integer
      default: 0
  
    ISIF:
      kind: integer
      default: 1
  
    MD_ALGO:
      kind: integer
      default: 0
    
    MAXSTEP:
      kind: float
      default: 0.1

    ALPHA:
      kind: float
      default: 70.0

    DT:
      kind: float
      default: 0.1
    
    DTMAX:
      kind: float
      default: 1.0

    NMIN:
      kind: integer
      default: 5

    FINC:
      kind: float
      default: 1.1

    FDEC:
      kind: float
      default: 0.5

    ASTART:
      kind: float
      default: 0.1
    
    FA:
      kind: float
      default: 0.99

    A:
      kind: float
      default: 0.1

    DAMPING:
      kind: float
      default: 1.0

    POTENTIAL:
      kind: string
      default: "OCP"

    NIMAGE:
      kind: integer
      default: 3

    POTIM:
      kind: float
      default: 1.0
    
    ICHAIN:
      kind: integer
      default: 1
      values:
         - 0
         - 1
         - 2
         - 3
