  options:
    IOPT:
      kind: integer
      default: 0

    IBRION:
      kind: integer
      default: 0

    NSW:
      kind: integer
      default: 100
  
    EDIFFG:
      kind: float
      default: -0.01
  
    POTIM:
      kind: integer
      default: 0
  
    ISIF:
      kind: integer
      default: 1
  
    MD_ALGO:
      kind: integer
      default: 0
